powersync-ja/powersync-service

- service/README.md
Correct, and full, Github links for Docker Hub.
> Correct Github links

- .changeset/sour-tables-battle.md
- packages/service-core/package.json
- pnpm-lock.yaml
The current version range for the `lru-cache` package is `^10.0.1`. Version `10.2.0` contains a broken import/export declaration in its `package.json` file.  The `mjs` folder is not present in the `dist` folder. 
Updating the version range will ensure consumers of the `@powersync/service-core` package don't install the broken version.
> [Fix] Update lru-cache package

- packages/service-core/package.json
- packages/service-core/src/storage/mongo/db.ts
- packages/service-core/src/storage/mongo/util.ts
- pnpm-lock.yaml
- service/package.json
Bump mongodb driver to fix "TypeError: "Cannot convert a BigInt value to a number" - [NODE-6165](https://jira.mongodb.org/browse/NODE-6165) / https://github.com/mongodb/node-mongodb-native/pull/4109
This typically occurred when a new MongoDB primary was selected while data queries are active.
> Fix "Cannot convert a BigInt value to a number"

- packages/rsocket-router/src/router/types.ts
- packages/service-core/src/metrics/Metrics.ts
- packages/service-core/src/replication/ErrorRateLimiter.ts
- packages/service-core/src/storage/MongoBucketStorage.ts
- packages/service-core/src/storage/mongo/MongoBucketBatch.ts
- packages/service-core/src/storage/mongo/PersistedBatch.ts
- packages/service-core/src/util/config/compound-config-collector.ts
- packages/types/src/config/PowerSyncConfig.ts
Improve replication logging to include additional debug info, such as batch size and current oplog position.
Before:
```
powersync_abc_10_def Flushing 610 ops
```
Now:
```
12:44:54.889 INFO powersync_10 Flushed 610 + 0 + 610 updates, 359kb. Last op_id: 2459024
```
Also reduce the 5s delay between connection attempts to 500ms, since this delay is always triggered when updating sync rules.
> Improve logging & reduce sync rule update delay

- .changeset/happy-flies-tease.md
- .changeset/smooth-frogs-wait.md
- .gitignore
- packages/rsocket-router/package.json
- packages/rsocket-router/src/router/ReactiveSocketRouter.ts
- packages/rsocket-router/src/router/transport/WebSocketServerTransport.ts
- packages/rsocket-router/src/router/transport/WebsocketDuplexConnection.ts
- packages/rsocket-router/tests/src/requests.test.ts
- packages/rsocket-router/tests/src/socket.test.ts
- packages/service-core/src/routes/router.ts
- packages/service-core/src/routes/socket-route.ts
- pnpm-lock.yaml
- service/src/runners/server.ts
- service/tsconfig.json
Recent alerts have shown uncaught exceptions for clients using the WebSockets connection method. Two main issues were identified.
In some circumstances the WebSocket might close unexpectedly. If the server tried to write data to this port an unhandled exception would be thrown. 
```
WebSocket is not open: readyState 2 (CLOSING)
```
An investigation led to this issue https://github.com/websockets/ws/issues/1515.
This PR adds better error and closed socket handling to the `WebSocketDuplexConnection` and `WebSocketServerTransport` implementations provided by RSocket. 
A unit test has been added to ensure no unhandled exceptions are thrown when the client closes the WebSocket. 
Some reports of the server failing to handle WebSocket frames were received.
This was reproducible by sending …
> [Fix] WebSocket Close Bugs

- .changeset/tender-emus-beat.md
- .changeset/tender-emus-drum.md
- packages/jpgwire/src/pgwire_node.js
- packages/service-core/src/replication/WalStream.ts
- packages/service-core/src/storage/mongo/OperationBatch.ts
The previous logic for reading from a postgres socket would read all available data, then "unshift" any "unused" data back onto the socket.
This meant that:
1. Backpressure on the socket did not function, which could cause the internal buffer to grow indefinitely.
2. As the internal buffer grew, reading got slower.
Those two issues compounded, resulting in much slower reads, and high memory usage. This would happen any time a lot of data is sent over the socket - specifically initial snapshot replication of large tables, but could also affect logical replication.
The fix is to just read as much data as requested.
The previous logic would do an explicit "flush" for every chunk of rows read for the initial table snapshot. These chunks are quite small - as little as 16KB each, which made …
> Fix snapshot performance issues

- .changeset/witty-ducks-work.md
- packages/service-core/src/routes/socket-route.ts
- packages/service-core/src/routes/sync-stream.ts
- packages/service-core/src/util/protocol-types.ts
- packages/service-core/test/src/sync_rules.test.ts
This PR introduces the ability to pass parameters from a client SDK to the sync rules.
Parameters are available in the sync rules under `user_parameters` (only supported `token_parameters` until now). Client PR [here](https://github.com/powersync-ja/powersync-js/pull/204) 
For example:
```
bucket_definitions:
user_lists:
parameters: select id as list_id from lists where owner_id = user_parameters.client_variable_test
data:
- SELECT * FROM lists where id = bucket.list_id
```
Verified values pull through via self-host project.
> feature: Added support for user parameters in sync rules.

- .changeset/stale-walls-mix.md
- packages/jpgwire/package.json
- packages/jpgwire/src/util.ts
- packages/service-core/test/src/pg_test.test.ts
- pnpm-lock.yaml
Dates such as `0022-02-03 12:13:14+03` previously caused the entire replication to fail and restart. This fixes the parsing to handle a wider date range, and return null for dates not supported at all.
> Fix date parsing in replication

- .changeset/rotten-candles-float.md
- packages/service-core/src/runner/teardown.ts
If we fail to connect to the postgres instance, the process does not terminate (errors such as `PgError: getaddrinfo ENOTFOUND`). I tried to find the cause using [wtfnode](https://www.npmjs.com/package/wtfnode), but it did not report anything significant. The workaround of `process.exit()` works.
This also adds better logging to the teardown job.
> Fix teardown process not exiting after errors

- README.md
Fixes a typo in the link for the `rsocket-router` package in the README.
> docs: update link to rsocket-router package readme

- .changeset/sour-beers-cover.md
- packages/sync-rules/package.json
- packages/sync-rules/src/SqlBucketDescriptor.ts
- packages/sync-rules/src/SqlSyncRules.ts
- packages/sync-rules/test/src/sql_functions.test.ts
- packages/sync-rules/test/src/sql_operators.test.ts
- packages/sync-rules/test/src/sync_rules.test.ts
- packages/sync-rules/test/tsconfig.json
- packages/sync-rules/vitest.config.ts
- pnpm-lock.yaml
This version picks up the schema issue correctly (array of parameter queries):
While this one doesn't (single parameter query):
The issue was the schema not being passed to the function in this specific case, causing schema validation to be bypassed.
This PR also moves pure sync-rule related tests to the sync-rules package, which simplifies the testing cycle a bit.
> Fix schema validation of parameter queries

- .changeset/cyan-doors-tap.md
- .github/workflows/development_image_release.yaml
- .github/workflows/development_packages_release.yaml
- .github/workflows/packages_release.yaml
- .github/workflows/test.yml
- packages/sync-rules/README.md
- packages/sync-rules/src/SqlDataQuery.ts
- packages/sync-rules/src/SqlParameterQuery.ts
- packages/sync-rules/src/StaticSqlParameterQuery.ts
- packages/sync-rules/src/sql_filters.ts
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/src/sql_support.ts
- packages/sync-rules/src/types.ts
- packages/sync-rules/test/src/data_queries.test.ts
- packages/sync-rules/test/src/parameter_queries.test.ts
- packages/sync-rules/test/src/static_parameter_queries.test.ts
- packages/sync-rules/test/src/sync_rules.test.ts
- packages/sync-rules/test/src/util.ts
This is an initial refactoring to allow some types of expressions on token_parameters and user_parameters.
Examples that this now supports (see tests for more):
```sql
SELECT id from users WHERE filter_param = token_parameters.some_param ->> 'description'
SELECT id from users WHERE filter_param = upper(token_parameters.some_param)
SELECT id from projects WHERE page = user_parameters.index + 1
```
These expressions are only supported for parameter queries, not for bucket parameters in data queries.
Additionally this:
* Expands test coverage for sync rules.
* Refactors internal naming to make concepts easier to follow.
* Adds overview documentation on the implementation.
> Expressions on parameters

- DEVELOP.md
- README.md
This fixes some oversights in the README files.
This was highlighted [here](https://github.com/powersync-ja/powersync-service/issues/8#issuecomment-2209554745)
> [Chore] Readme notes

- .changeset/cuddly-numbers-hope.md
- .changeset/tame-planes-argue.md
- packages/service-core/src/auth/JwtPayload.ts
- packages/service-core/src/auth/KeyStore.ts
- packages/service-core/src/routes/endpoints/socket-route.ts
- packages/service-core/src/routes/endpoints/sync-stream.ts
- packages/service-core/src/sync/sync.ts
- packages/service-core/test/src/data_storage.test.ts
- packages/service-core/test/src/sync.test.ts
- packages/sync-rules/README.md
- packages/sync-rules/src/SqlBucketDescriptor.ts
- packages/sync-rules/src/SqlDataQuery.ts
- packages/sync-rules/src/SqlParameterQuery.ts
- packages/sync-rules/src/SqlSyncRules.ts
- packages/sync-rules/src/StaticSqlParameterQuery.ts
- packages/sync-rules/src/index.ts
- packages/sync-rules/src/json_schema.ts
- packages/sync-rules/src/request_functions.ts
- packages/sync-rules/src/sql_filters.ts
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/src/sql_support.ts
- packages/sync-rules/src/types.ts
- packages/sync-rules/src/utils.ts
- packages/sync-rules/test/src/data_queries.test.ts
- packages/sync-rules/test/src/parameter_queries.test.ts
- packages/sync-rules/test/src/static_parameter_queries.test.ts
- packages/sync-rules/test/src/sync_rules.test.ts
- packages/sync-rules/test/src/util.ts
Adds new functions, for use in parameter queries only:
1. `request.jwt()`: Returns the entire (signed) JWT payload as a JSON string.
2. `request.parameters()`: Returns the client parameters (unauthenticated) as a JSON string.
3. `request.user_id()`: Returns the token subject, same as `token_parameters.user_id()`.
These are similar to the current `token_parameters` and `user_parameters` (added in #7) respectively. The major differences are that the entire payloads are preserved as-is, which can make usage a little more intuitive. It also includes JWT payload fields not previously accessible.
Examples:
```sql
request.jwt() ->> 'sub' -- Same as token_parameters.user_id. Makes it clear which JWT field is used.
request.user_id() -- Same as `request.jwt() ->> 'sub'` and …
```
> Support for `request.parameters()`

- .changeset/stale-hounds-tell.md
- packages/service-core/src/routes/route-register.ts
This fixes an omission from https://github.com/powersync-ja/powersync-service/pull/24. 
Errors thrown in Router endpoints should be logged.
A sample production log is included below
```json
{
"errorData": {
"code": "AUTHORIZATION",
"description": "Authorization failed",
"details": [
"Could not find an appropriate key in the keystore. The key is missing or no key matched the token KID"
],
"name": "AuthorizationError",
"status": 401
},
"is_journey_error": true,
"level": "error",
"message": "Request failed [AUTHORIZATION] Authorization failed\n  Could not find an appropriate key in the keystore. The key is missing or no key matched the token KID",
"name": "AuthorizationError",
"stack": "AuthorizationError: [AUTHORIZATION] Authorization failed\n  Could not find an appropriate key in the …
```
> [Fix] Missing router error logs

- .changeset/silly-impalas-walk.md
- libs/lib-services/src/errors/framework-errors.ts
- packages/rsocket-router/src/router/ReactiveSocketRouter.ts
#24 introduced concurrency limits for websockets, similar to what we had with http streams. However, the connection count does not always decrease when a connection is closed, leading to all clients eventually getting an error " [429] Maximum active concurrent connections limit has been reached".
This simplifies it a bit by just tracking the number of websocket clients on the websocket server, instead of attempting to track the individual streams. We could additionally limit the number of streams per client in the future.
> Fix concurrency limit for websockets

- .changeset/config.json
- .github/workflows/image_release.yaml
- package.json
- service/CHANGELOG.md
- service/package.json
The release process for the open edition DockerHub image is currently manually triggering the `Docker Image Release` action after the Changesets `Version` PR has been merged. It's easy to forget to trigger this action. 
The Docker image is built (and versioned) from the `powersync-open-service` private package (located in the `service` folder).
This PR configures Changesets to tag the `powersync-open-service` (private) "package" when publishing. The publish action will then run after tags have been pushed. [Refference](https://github.com/changesets/changesets/blob/main/docs/versioning-apps.md)
This will also create Github releases for `powersync-open-service` which will notify watchers of the repo about Docker image releases.
Side note: Do we want to rename `powersync-open-service` to …
> [Chore] Automatically trigger DockerHub release

- .changeset/brown-horses-whisper.md
- packages/sync-rules/src/ExpressionType.ts
- packages/sync-rules/src/SqlDataQuery.ts
- packages/sync-rules/test/src/data_queries.test.ts
- packages/sync-rules/test/src/util.ts
Previously, this data query would report an error `Query must return an "id" column`:
```
select name from mytable
```
However, this would not:
```
select * from mytable
```
Now, the above would give a warning if `mytable` does not have an id column defined.
> Validate id column for "select *"

- .changeset/plenty-dryers-look.md
- packages/service-core/src/routes/endpoints/socket-route.ts
- packages/service-core/src/routes/endpoints/sync-stream.ts
- packages/service-core/src/sync/RequestTracker.ts
- packages/service-core/src/sync/sync.ts
- packages/service-core/src/sync/util.ts
- packages/service-core/test/src/sync.test.ts
This additionally adds some additional fields to structured logs, for easier processing if desired.
Sample log output for a single HTTP request:
```
info: New checkpoint: 2686394 | write: null | buckets: 2 ["global[]","by_user[\"test\"]"] {"buckets":2,"checkpoint":"2686394","user_id":"test"}
info: Sync stream complete {"data_synced_bytes":14291587,"operations_synced":2402,"user_id":"test"}
info: POST /sync/stream {"duration_ms":181,"method":"POST","path":"/sync/stream","route":"/sync/stream","status":200}
```
JSON log format:
```json
{"buckets":2,"checkpoint":"2686394","level":"info","message":"New checkpoint: 2686394 | write: null | buckets: 2 [\"global[]\",\"by_user[\\\"test\\\"]\"]","timestamp":"2024-07-17T09:05:33.532Z","user_id":"test"} …
```
> Log user_id and sync stats for each connection

- .changeset/nasty-mugs-battle.md
- packages/rsocket-router/src/router/transport/WebSocketServerTransport.ts
- packages/rsocket-router/tests/src/socket.test.ts
When closing a WebSocket connection, e.g. by closing a web tab, the router did not immediately detect that the connection has been closed.
The connection would close when the keep-alive ping-pong check failed, but the delay could cause the number of concurrent connections and active streams to accumulate for short periods. 
This bubbles the WebSocket `close` event through the WebSocket Duplex connection and router endpoint handlers.
Thanks @rkistner for finding the issue and providing a fix.
This was tested locally with web and React Native. See screenshots below where the `STREAM` log duration is below the keep-alive period of 30_000ms.
The close unit test was updated to ensure that the cancel event is called correctly. Oddly enough this extended test actually would pass with the …
> [Fix] WebSocket Close

- .changeset/popular-rivers-smell.md
- service/src/runners/server.ts
For websocket connections, the authentication token is provided on the connection setup (RSocket SETUP frame).
The current implementation parsed the token in the connection setup via the `contextProvider`, but only checked that it was valid in the RSocket stream. It would then close the RSocket stream if authentication failed, while the websocket itself stayed open.
This now adds the same validation on the connection level via the `contextProvider`. This causes the entire websocket to be closed when authentication fails.
We have no websocket routes using anonymous authentication, so proper per-route auth is not a consideration now.
There is probably a bug on journey-js as well. It appears to currently re-create the entire connection if a RSocket stream errors, without closing the previous …
> Require authentication on websocket connection level

- .changeset/dry-schools-rush.md
- docs/README.md
- docs/bucket-properties.md
- docs/compacting-operations.md
- docs/sync-protocol.md
- packages/service-core/src/entry/cli-entry.ts
- packages/service-core/src/entry/commands/compact-action.ts
- packages/service-core/src/entry/entry-index.ts
- packages/service-core/src/storage/BucketStorage.ts
- packages/service-core/src/storage/mongo/MongoCompactor.ts
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
- packages/service-core/src/storage/mongo/models.ts
- packages/service-core/src/storage/mongo/util.ts
- packages/service-core/src/sync/sync.ts
- packages/service-core/test/src/__snapshots__/sync.test.ts.snap
- packages/service-core/test/src/bucket_validation.test.ts
- packages/service-core/test/src/bucket_validation.ts
- packages/service-core/test/src/compacting.test.ts
- packages/service-core/test/src/data_storage.test.ts
- packages/service-core/test/src/slow_tests.test.ts
- packages/service-core/test/src/sync.test.ts
- packages/service-core/test/src/util.ts
- packages/service-core/test/src/wal_stream_utils.ts
Implement a `compact` command that compacts all buckets in the instance. See the new documentation for what exactly it does.
This is currently a separate manual command, and not run automatically. It can be run manually or on a schedule.
This does not implement defragmentation yet. For some use cases it may be beneficial to trigger defragmentation from the postgres side using a periodic query such as `update mytable set id = id where updated_at < now() - interval '1 week'`, after which the compact command will be able to efficiently compact historical operations.
The memory used by the command can be controlled using the `--max-old-space-size` config for NodeJS. 256MB should be enough for up to 1M unique rows per bucket.
This is the first implementation using MOVE and CLEAR operations. …
> Compacting buckets

- .changeset/purple-moles-shave.md
- packages/service-core/src/entry/commands/compact-action.ts
- packages/service-core/src/storage/BucketStorage.ts
- packages/service-core/src/storage/mongo/MongoCompactor.ts
Follows on #37.
1. Use the correct storage database for the compact action. Previously it would only work if the database was specified in the URI.
2. Add an API to compact specific buckets instead of all buckets.
> Compact fixes

- .changeset/fair-planes-flow.md
- packages/rsocket-router/src/router/ReactiveSocketRouter.ts
- packages/service-core/src/routes/configure-fastify.ts
- packages/service-core/src/routes/configure-rsocket.ts
- packages/service-core/src/routes/endpoints/socket-route.ts
- packages/service-core/src/routes/route-register.ts
- packages/service-core/src/routes/router-socket.ts
- packages/service-core/src/routes/router.ts
- packages/service-core/src/routes/routes-index.ts
- packages/service-core/src/sync/sync-index.ts
- service/src/runners/server.ts
The `@powersync/service-core` package currently exports various route definitions and some functions for registering the routes on a server. 
Routes are usually registered in the `server` runner inside the project `service` folder/package. The current configuration required duplication of the route registration between different projects. 
This PR introduces utility functions which perform the common route registration. The registration itself is still configurable if projects require custom functionality.
> [Chore] Neaten Routes

- pnpm-lock.yaml
- pnpm-workspace.yaml
- test-client/README.md
- test-client/package.json
- test-client/src/auth.ts
- test-client/src/bin.ts
- test-client/src/client.ts
- test-client/src/index.ts
- test-client/src/ndjson.ts
- test-client/src/util.ts
- test-client/tsconfig.json
Add an example NodeJS client that retrieves the raw operation data.
Apart from type definitions, the client uses minimal powersync dependencies, to attempt to be a standalone example.
See the readme for details.
> Add test client

- .github/workflows/packages_release.yaml
This fixes a bug in the DockerHub release workflow. See the failed run [here](https://github.com/powersync-ja/powersync-service/actions/runs/10286203733/job/28466299830)
This action failed due to the `jq` test returning a non-zero exit code. The exit code is required in order to determine if the service image was released.
This fix allows using the return code in the following `if` block.
This was tested locally by adding the action code into a `test.sh` file which was executed with different `$package` variables. The `echo` lines were modified for demonstrtion.
> chore: fix release workflow

- test-client/src/auth.ts
- test-client/src/bin.ts
A self-hosted setup often uses `powersync-dev` as the audience, instead of the endpoint URL. This updates the generate-token script to include the endpoint URL as an additional audience. This defaults to `http://127.0.0.1:<port>`. but can be customized.
This also increases the token expiry from 1h to 24h.
Combined with https://github.com/powersync-ja/powersync-js/pull/264, this helps streamline usage of the diagnostics app for local development.
Sample:
```
pnpm generate-token -c ../service/powersync.yaml 
> test-client@0.1.0 generate-token /home/ralf/src/powersync-service/test-client
> tsc -b && node dist/bin.js generate-token "-c" "../service/powersync.yaml"
Payload:
{
"sub": "test_user",
"iat": 1723548362,
"iss": "test-client",
"aud": [
"powersync-dev",
"http://127.0.0.1:8080"
], …
```
> [test-client] Include endpoint as additional audience

- .changeset/thirty-bikes-move.md
- packages/sync-rules/src/JsLegacySchemaGenerator.ts
- packages/sync-rules/src/TsSchemaGenerator.ts
- packages/sync-rules/src/generators.ts
- packages/sync-rules/src/index.ts
- packages/sync-rules/test/src/sync_rules.test.ts
We have been recommending this syntax for a while - the generator should use this by default.
We can still give the option of the old syntax for apps not wanting to switch.
The generator here includes the entire "schema" file, including imports and exports.
> Add TableV2 / TypeScript schema generator

- .changeset/plenty-ads-matter.md
https://github.com/powersync-ja/powersync-service/pull/49/files added a log entry for the number of currently connected WebSockets. This change is useful for debugging, but since no Changeset was added for this - no package version bump was done and the changes are not present downstream. The open edition has the change due to the Docker image copying the package from the repo source.
> [Fix] Add missing changeset

- .changeset/tricky-phones-tell.md
- packages/service-core/src/sync/sync.ts
Lock sync lock stats when get close to the concurrency limit. This should give us an indication if/when this lock is the cause of sync issues.
> Log sync lock

- .changeset/rude-timers-matter.md
- packages/service-core/src/routes/configure-rsocket.ts
- packages/service-core/src/routes/endpoints/checkpointing.ts
- packages/service-core/src/routes/endpoints/socket-route.ts
- packages/service-core/src/routes/endpoints/sync-stream.ts
- packages/service-core/src/routes/router-socket.ts
- packages/service-core/src/routes/router.ts
- packages/service-core/src/sync/sync.ts
- packages/service-core/src/util/protocol-types.ts
- packages/service-core/src/util/utils.ts
- service/src/runners/server.ts
1. Support client_id parameter.
1. This specifically affects write checkpoints (limits write checkpoints to a specific client, rather than just an user).
2. The id is generated by the client and not sure on its own, so we still scope per user_id.
2. Allow User-Agent and X-User-Agent headers.
1. This allows us to identify which client is used.
> Support client_id and User-Agent

- .changeset/stale-llamas-shave.md
- packages/service-core/src/routes/endpoints/socket-route.ts
This adds the `client_id` from https://github.com/powersync-ja/powersync-service/pull/64  to the logs for WebSocket sync endpoints.
> [Fix] Add log to WebSocket Endpoint

- .changeset/tricky-parents-mate.md
- packages/rsocket-router/src/router/transport/WebsocketDuplexConnection.ts
- packages/rsocket-router/tests/src/socket.test.ts
The issue was that the `removeAllListeners()` on close also removes the error handler. So if an error on the socket is triggered after closing, it ended up as an uncaught exception, crashing the process.
This only appears to happen when there is a combination of:
1. The socket is closed by the server, e.g. from a keepalive timeout.
2. A lot of data to be sent is buffered.
This may reduce the need for some of the workarounds implemented in https://github.com/powersync-ja/powersync-service/pull/11, although they probably don't hurt.
> Fix `WebSocket is not open: readyState 2 (CLOSING)`

- .changeset/dull-foxes-explode.md
- packages/rsocket-router/src/router/ReactiveSocketRouter.ts
- packages/rsocket-router/src/router/SocketRouterListener.ts
- packages/rsocket-router/src/router/types.ts
- packages/rsocket-router/tests/src/requests.test.ts
- packages/service-core/src/routes/endpoints/socket-route.ts
- packages/service-core/src/sync/sync.ts
A race conditions with websocket handling could cause the route handler to "hang" indefinitely, after the underlying connection is closed. This surfaces in two ways:
1. The "concurrent connections" metric reports these as connections, giving a slow increase in connection count over time.
2. The `syncSemaphore` could permanently hold on to a lock for these, eventually leading to no locks being available, and no users able to sync.
While the race condition is rare, it does build up over time.
In tests I could trigger the race condition in two places:
1. Closing a connection before `observer.registerListener()` is called, by setting `lifetime: 0` on the client. I'm not sure whether this ever happened in practice.
2. Close the connection after next batch of data is retrieved, but before the …
> Fix hanging streams

- .changeset/shiny-bees-heal.md
- packages/sync-rules/package.json
- packages/sync-rules/src/TsSchemaGenerator.ts
- packages/sync-rules/test/src/sync_rules.test.ts
- pnpm-lock.yaml
Now that we have merged `TableV2` and `Table` we can change the generated schema to only use `Table`.
* Replaced `TableV2` with `Table`
* Updated vitest package
> chore(sync-rules): change TableV2 to Table

- packages/service-core/src/util/protocol-types.ts
These are artifacts from an old prototype that used separate http requests for downloading data, instead of a single streaming request.
The crud API has also been removed in the meantime.
> Remove some unused protocol types

- .changeset/short-bats-sin.md
- packages/sync-rules/src/SqlDataQuery.ts
- packages/sync-rules/src/SqlParameterQuery.ts
- packages/sync-rules/src/StaticSqlParameterQuery.ts
- packages/sync-rules/src/sql_filters.ts
- packages/sync-rules/test/src/data_queries.test.ts
- packages/sync-rules/test/src/parameter_queries.test.ts
- packages/sync-rules/test/src/static_parameter_queries.test.ts
For queries such as `SELECT * FROM assets WHERE userId = bucket.userId`, both instances of `userId` are converted to a lower-case `userid`. This is standard behavior in Postgres SQL, and common in other SQL variations as well. However, it is often unexpected for developers, causing difficult-to-debug issues.
This adds a warning when an unquoted identifier is used that is not all lower-case. We don't get enough info to properly split schema name, table name and table alias, so the check does nothing for now if a schema name or table alias is encountered.
The check is especially relevant when schema information is not available for validations.
> Warn on table/column identifier case issues

- .changeset/stupid-maps-buy.md
- packages/service-core/src/storage/ChecksumCache.ts
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
- packages/service-core/src/storage/mongo/util.ts
- packages/service-core/src/util/utils.ts
- packages/service-core/test/src/checksum_cache.test.ts
- packages/service-core/test/src/compacting.test.ts
The checksum cache works not just by caching specific checksum queries, but also by re-using earlier checksums and just adding the partial checksum of any newer operations on the bucket, which can be significantly faster than recalculating the entire checksum from scratch.
Compacting a bucket guarantees that the final checksum for the bucket stays the same. However, there is one edge case:
```js
// 1. Start with:
{ op_id: 1, op: 'PUT', row_id: 'A', checksum: 1 },
// 2. Lookup and cache the checksum (1).
// 3. Insert rows:
{ op_id: 2, op: 'PUT', row_id: 'A', checksum: 2 },
{ op_id: 3, op: 'PUT', row_id: 'A', checksum: 4 }
// The checksum is now 7 (but we don't cache in this example)
// 4. Compact to:
{ op_id: 2, op: 'CLEAR', checksum: 3 },
{ op_id: 3, op: 'PUT', row_id: 'A', checksum: 4 } …
```
> Fix checksum cache with compacting

- .changeset/young-rockets-behave.md
- packages/service-core/src/replication/WalStream.ts
Fixes #86.
We use `pg_logical_slot_peek_binary_changes` to peak up to 1000 changes to check slot health on startup.
If the peaked changes are large, this can add significant processing and memory overhead, potentially leading to out-of-memory errors such as #86.
This changes to streaming results, as well as removing the large binary data from the results, to avoid that issue.
> Reduce memory usage of slot health check

- modules/module-mongodb/src/api/MongoRouteAPIAdapter.ts
- packages/types/src/definitions.ts
This reverts sone API facing type changes from [here](https://github.com/powersync-ja/powersync-service/pull/90/files#diff-01ef33ad4cd133d7161fe4d3ffd0dbf5acd29cd8480ea9f25fcb954f62376087). The deprecated `type` and `pg_type` are expected in upstream consumers of the service routes. This PR sets the values explicitly to the recommended alternative, `internal_type`. 
This fixes schema querying in the PowerSync dashboard.
> [MongoDB] Schema Endpoint Fix

- .changeset/funny-pianos-allow.md
- packages/service-core/src/db/mongo.ts
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
Fixes "operation exceeded time limit" error displayed when clearing large amounts of bucket data after a sync rule update.
The error resolved automatically, but often caused confusion.
> Immediately retry clear operations on timeout

- .changeset/green-books-shout.md
- packages/service-core/src/storage/BucketStorage.ts
- packages/service-core/src/storage/MongoBucketStorage.ts
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
- packages/service-core/src/storage/mongo/db.ts
- packages/service-core/test/src/data_storage.test.ts
- packages/service-core/test/src/sync.test.ts
- packages/service-core/test/src/util.ts
Fix storageStats error in metrics endpoint when the collections don't exist.
Fixes #81.
Also removes the unused `setSnapshotDone()` function.
> Fix storageStats error

- .changeset/cold-items-explain.md
- modules/module-mongodb/src/api/MongoRouteAPIAdapter.ts
On an Atlas M10 instance with views, `listCollections()` lists `system.views`, but we're not authorized to query it.
This fixes the issue on two levels:
1. Filter out system collections.
2. Ignore `Unauthorized` errors when sampling data.
> Ignore Unauthorized errors on collections for MongoDB schema

- .changeset/funny-pianos-allow.md
- .changeset/green-books-shout.md
- .changeset/short-bats-sin.md
- .changeset/stupid-maps-buy.md
- .changeset/wet-gorillas-remember.md
- .changeset/young-rockets-behave.md
- packages/service-core/CHANGELOG.md
- packages/service-core/package.json
- packages/service-core/src/db/mongo.ts
- packages/service-core/src/storage/BucketStorage.ts
- packages/service-core/src/storage/MongoBucketStorage.ts
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
- packages/service-core/src/storage/mongo/db.ts
- packages/service-core/test/src/data_storage.test.ts
- packages/service-core/test/src/sync.test.ts
- packages/service-core/test/src/util.ts
- packages/sync-rules/CHANGELOG.md
- packages/sync-rules/package.json
- service/CHANGELOG.md
- service/package.json
- test-client/CHANGELOG.md
- test-client/package.json
This updates the `feat/modular-replication-architecture` branch with the latest changes from the `main` branch.
> [Chore] Module/Main update

- .changeset/thirty-llamas-carry.md
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/test/src/sql_functions.test.ts
The `substring` function roughly matches the [SQLite substring function](https://sqlite.org/lang_corefunc.html#substr) (notably different from the JavaScript equivalent). It is also similar to the Postgres substring function, but different when a negative `start` or `length` is specified.
The `json_keys` function has no direct equivalent in Postgres or SQLite. Postgres has a similar `json_object_keys`, but that returns each key as a separate row, while we return the keys as a JSON array.
Use cases:
substring:
```sql
-- Parameter query - filter by date value
-- substring(created_at, 1, 10) returns the date portion of the timestamp
select id as post_id from posts where substring(created_at, 1, 10) in request.jwt() -> 'sync_dates'
```
json_keys:
```sql
-- Data query - permissions_json: …
```
> New sync rule functions: json_keys and substring

- .github/workflows/test.yml
- DEVELOP.md
- README.md
- service/README.md
MySQL no longer "coming soon".
Also minor terminology formatting
> Readme MySQL updates

- .changeset/fifty-dogs-reply.md
- modules/module-mongodb/src/replication/ChangeStream.ts
Currently, we always use a global changestream, which needs the `readAnyDatabase` permission on Atlas.
This is needed when sync rules reference multiple databases in the same cluster. We want to use a single changestream for the entire replication process, so having `read` permissions for each individual database is not sufficient when using multiple databases. Replicating multiple databses is not a common use case though, and the permissions needed is a problem for some users.
This now changes to opening a changestream on the specific database if only the default database is used. This effectively reduces the required permissions to just `read@mydb`.
So overall the current permissions required for Atlas are:
```
readWrite@mydb._powersync_checkpoints
readAnyDatabase@admin
```
And after …
> [MongoDB] Reduce permissions required

- .changeset/heavy-shirts-chew.md
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
- packages/service-core/test/src/data_storage.test.ts
- packages/service-core/test/src/util.ts
The `MongoSyncBucketStorage`'s `getParsedSyncRules` method currently caches the parsed sync rules with the assumption that the previously cached Sync rules were generated with the same `options`. This assumption is not always true. 
In some cases an external module could request parsed Sync rules without knowing the exact `defaultSchema`. This external request should not affect subsequent requests for parsed Sync rules. Currently this behaviour breaks syncing for schemas which are different from the cached schema.
> fix: Cached Parsed Sync Rules

- .changeset/eighty-coins-jog.md
- packages/service-core/package.json
- packages/types/src/config/normalize.ts
The currently restrict Postgres connections to ports in the range of [1024, 49151]. 
Certain local Postgres services, such as Supabase expose Postgres on port `54322` by default. This PR removes the restriction for connecting to "Ephemeral" [ports](https://en.wikipedia.org/wiki/Ephemeral_port) (ports > 49151). This allows for easier local development with Supabase and potentially other databases.
The check for "Privileged" [ports](https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html) is still maintained.
> feat: Postgres connection port (de)restrictions

- .changeset/eighty-coins-jog.md
- .changeset/funny-pianos-allow.md
- .changeset/green-books-shout.md
- .github/workflows/test.yml
- DEVELOP.md
- README.md
- modules/module-postgres/src/types/types.ts
- packages/service-core/CHANGELOG.md
- packages/service-core/package.json
- packages/sync-rules/CHANGELOG.md
- packages/sync-rules/package.json
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/test/src/sql_functions.test.ts
- service/CHANGELOG.md
- service/README.md
- service/package.json
- test-client/CHANGELOG.md
- test-client/package.json
This updates the Modular Architecture feature branch with the latest changes from `main`.
This includes changes from: 
- https://github.com/powersync-ja/powersync-service/pull/108
- https://github.com/powersync-ja/powersync-service/pull/112
- https://github.com/powersync-ja/powersync-service/pull/116
> [Chore] Modular Main Update

- packages/service-core/src/entry/commands/compact-action.ts
- packages/service-core/src/storage/BucketStorage.ts
- packages/service-core/src/storage/mongo/MongoCompactor.ts
This allows compacting specific buckets, instead of all buckets, when running a compact job manually.
Usage:
```sh
compact --buckets by_user
compact --buckets by_user["user1"]
compact --buckets global,by_user
```
> Option to compact specific buckets

- .changeset/healthy-rules-arrive.md
- modules/module-mysql/src/api/MySQLRouteAPIAdapter.ts
A recent change to the default of how JSON fields are returned from MySQL requires that we parse the JSON on the powersync side. Previously this was handled as part of the connection client.
> Parse returned mysql schema result

- modules/module-mongodb/src/replication/MongoRelation.ts
- modules/module-mongodb/test/src/mongo_test.test.ts
Minor fixes to how RegExp, MinKey and MaxKey are handled inside nested arrays or objects. Also adds more tests for the remaining BSON types.
With this, we should now support the full set of BSON types, as documented here: https://github.com/powersync-ja/mintlify-docs/pull/26
> [MongoDB] More types fixes

- .changeset/witty-maps-heal.md
- packages/service-core/src/routes/configure-fastify.ts
- packages/service-core/src/routes/endpoints/probes.ts
- packages/service-core/src/routes/router.ts
- packages/service-core/test/src/routes/probes.integration.test.ts
- packages/service-core/test/src/routes/probes.test.ts
Added probe endpoints which can be used for healthchecks by users. Startup to show the system has started up, liveness to show if the system is alive and readiness to show the system is ready.
* Added readiness, liveness, and startup endpoints
Added unit and integration testing for probes endpoint. 
Not sure if there is any other testing I should do?
> feat: add http probes for health checks

- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mongodb/test/src/change_stream.test.ts
- modules/module-mongodb/test/src/change_stream_utils.ts
- modules/module-mongodb/test/src/slow_tests.test.ts
Builds on #121.
Previously, we used `{snapshot: true}` to replicate an initial snapshot. That gives nice consistency guarantees, but cannot run longer than 5 minutes (configurable using [minSnapshotHistoryWindowInSeconds](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.minSnapshotHistoryWindowInSeconds)). So this caused replication of larger amounts of data to fail.
This fixes it to not use the snapshot mode anymore, but rather just make sure we replicate all incremental changes since the start of the snapshot. This means data modified during the snapshot may be replicated twice, but that should not cause any consistency issues.
Replication errors are only cleared once we successfully replicate some data (when `.commit(lsn)` is called). Development …
> [MongoDB] Fix initial snapshot / Better error recovery

- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mysql/src/replication/BinLogStream.ts
- modules/module-postgres/src/replication/WalStream.ts
- packages/service-core/src/storage/BucketStorage.ts
- packages/service-core/src/storage/mongo/MongoBucketBatch.ts
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
- packages/service-core/src/storage/mongo/OperationBatch.ts
- packages/service-core/test/src/util.ts
Builds on #121.
The current_data bucket storage collection stores the following data:
* `buckets`: The current set of buckets for each replicated row
* `lookups`: Current parameter query lookups for each replicated row
* `data`: A copy of the current data
Buckets and lookups are used to be able to do REMOVE operations (need to know in which buckets a row was before, so we know from which buckets we need to remove it from after an update).
The `data` bit is to support partial updates. For Postgres, this could be when we receive an update with unchanged TOAST columns. However, for MongoDB we get the full document on each update, so never need that. This adds an optimization for MongoDB to skip that persistence.
> [MongoDB] Skip current_data storage

- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mongodb/test/src/change_stream.test.ts
Builds on #129.
With MongoDB change streams, if you have very large updates, the 16MB document size limit can be reached with change stream event documents. This specifically affects updates of large fields, where the field can appear twice in the change stream event.
To handle this, MongoDB has the `$changeStreamSplitLargeEvent` option, which uses multiple change stream events for one logical update. This PR now uses that to fix the issue.
> [MongoDB] Handle split events

- packages/service-core/src/storage/mongo/MongoWriteCheckpointAPI.ts
- packages/service-core/test/src/sync.test.ts
With #105, write checkpoint filtering was broken during the refactoring. This fixes it again.
The effect of the bug is that write checkpoints could be reported to the client sooner than it should be, which could result in "flickering" of data. This may not be noticeable in many cases, but would be more common if there is replication lag due to high write volumes.
Note: The test does pass on the current `main` branch (although it has to be refactored a bit to run).
> [beta] Fix managed write checkpoint filtering

- .changeset/tender-vans-impress.md
- modules/module-mongodb/package.json
- modules/module-mongodb/src/replication/MongoErrorRateLimiter.ts
- modules/module-mysql/package.json
- modules/module-mysql/src/replication/MySQLErrorRateLimiter.ts
- modules/module-postgres/package.json
- package.json
- packages/rsocket-router/package.json
- packages/service-core/package.json
- packages/service-core/src/routes/endpoints/sync-rules.ts
- pnpm-lock.yaml
- service/package.json
- test-client/package.json
This prepares the `feat/modular-replication-architecture` branch for merging to the `main` branch. This PR addresses some comments from https://github.com/powersync-ja/powersync-service/pull/133.
Items Addressed:
- [Comment](https://github.com/powersync-ja/powersync-service/pull/133#discussion_r1856523066), Removed Postgres error message from MongoDB error rate limiter.
- [Comment](https://github.com/powersync-ja/powersync-service/pull/133#discussion_r1856583433), Removed Postgres error message from MySQL error rate limiter.
- [Comment](https://github.com/powersync-ja/powersync-service/pull/133#discussion_r1856594290) Shared dev dependency versions in monorepo
- [Comment](https://github.com/powersync-ja/powersync-service/pull/133#discussion_r1856622555) Removed unused import
- …
> Modular Architecture Prep for Merge

- .changeset/dry-walls-sleep.md
- packages/service-core/src/entry/commands/compact-action.ts
Fixes regression from #120. This caused any compact action to fail with `Fatal error Cannot read properties of undefined (reading 'join')` - both self-hosted and cloud versions.
> Fix compact action

- .changeset/green-forks-approve.md
- modules/module-postgres/src/auth/SupabaseKeyCollector.ts
- packages/service-core/src/auth/KeySpec.ts
- packages/service-core/src/auth/StaticSupabaseKeyCollector.ts
- packages/service-core/src/auth/auth-index.ts
- packages/service-core/src/util/config/compound-config-collector.ts
- packages/types/src/config/PowerSyncConfig.ts
This adds a new `supabase_jwt_secret` config option. This can be set to the same value as the deprecated `app.settings.jwt_secret` value, without any additional config.
Specifically, this does:
1. Avoid needing boilerplate for key type and alg.
2. Avoid needing to specify the audience "authenticated".
3. Increase the max key lifetime to match Supabase (1 week),
4. Automatically base64-url-encode the key.
The idea is this would allow just copying the Supabase JWT key from the Supabase project dashboard, without any more complications.
As soon as Supabase rolls out asymmetric keys, we can deprecate this workflow.
> Supabase static keys - simplified config

- .changeset/plenty-poets-tan.md
- modules/module-postgres/src/module/PostgresModule.ts
When a secret is explicitly configured, disable the SupabaseKeyCollector that uses `current_setting('app.settings.jwt_secret')`.
This helps to:
1. Make it easier to see when the secret is incorrectly configured (versus working now and failing at a later date).
2. Avoid errors in the logs when failing to lookup `current_setting('app.settings.jwt_secret')`, despite the hardcoded secret being configured.
> Disable SupabaseKeyCollector when a secret is configured

- .changeset/swift-ways-live.md
- packages/sync-rules/package.json
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/test/src/sql_functions.test.ts
- pnpm-lock.yaml
In our project we use base64 encoded uuids on the client, for faster indexes and joins. 
This PR adds a function to convert the underline uuid bytes into base64, alternatively there could be a function to convert to just bytes and then use the base64 sync rule function. Let us know what you think is best.
This is our Discord discussion: https://discord.com/channels/1138230179878154300/1312036536849666118
> Sync rules function to convert uuid to base64

- .changeset/tender-lions-hope.md
- modules/module-postgres/src/api/PostgresRouteAPIAdapter.ts
- modules/module-postgres/src/module/PostgresModule.ts
- modules/module-postgres/test/src/util.ts
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/test/src/sql_functions.test.ts
On most Postgres versions, `pg_logical_emit_message()` returns the correct current LSN. However, on Aurora (Postgres compatible), it can return an entirely different LSN in some (but not all) cases, causing the write checkpoints to never be replicated back to the client. To cater for those cases, we now use `pg_current_wal_lsn()` to get the correct LSN.
Both queries are done in a single pgwire query call, so it is still a single round-trip with minimal overhead.
> Write checkpoint workaround for Aurora Postgres

- .changeset/six-rings-greet.md
- modules/module-postgres/src/api/PostgresRouteAPIAdapter.ts
Fixes this error showing up in the logs:
```
Unable to get replication lag Could not determine replication lag for slot [object Object]
```
This does not affect end-users, and we don't actually display that in the instance diagnostics yet. So it was primarily an issue of confusing developers when they view the logs.
> [Postgres] Fix replication lag diagnostics

- .changeset/chilled-bears-kneel.md
- .changeset/young-rings-fold.md
- modules/module-postgres/src/replication/PgManager.ts
- modules/module-postgres/src/replication/WalStream.ts
- packages/jpgwire/src/pgwire_node.js
Builds on #150.
This configures both TCP keepalive and connection timeouts, to detect broken snapshot connections in around 30 seconds instead of 6 minutes.
This now also uses `DECLARE CURSOR` and `FETCH` to fetch data in batches, instead of one large stream. This may reduce the chance of these connections hanging.
> [Postgres] Improve timeouts and table snapshots

- .changeset/perfect-fireants-warn.md
- modules/module-mongodb/package.json
- modules/module-postgres/test/src/large_batch.test.ts
- packages/service-core/package.json
- packages/service-core/src/storage/mongo/MongoCompactor.ts
- packages/service-core/src/storage/mongo/MongoWriteCheckpointAPI.ts
- packages/service-core/src/storage/mongo/PersistedBatch.ts
- packages/service-core/src/storage/mongo/util.ts
- pnpm-lock.yaml
- service/package.json
Sample error seen during replication:
```
MongoBulkWriteError: BSONObj size: 16814023 (0x1008FC7) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "bucket_data"
```
This appears to be a regression in v6.10.0 of the MongoDB NodeJS driver, which we're using on the cloud service.
See the comments for details on the issue and the fix. I'll file a driver bug report after we get this out.
> Fix bulkWrite BSON error

- .changeset/moody-cobras-walk.md
- modules/module-mongodb/src/module/MongoModule.ts
- modules/module-mongodb/src/replication/MongoManager.ts
- modules/module-postgres/src/module/PostgresModule.ts
This is relevant for testing connections on the cloud dashboard. Currently the worker_thread is killed before the connection times out. The shorter timeout will ensure we get a proper error when failing to connect.
> [MongoDB] Short timeout for testing connections

- .changeset/clever-tomatoes-sip.md
- modules/module-postgres/src/replication/WalStream.ts
Reverts the DECLARE CURSOR change from #152. It appears to fail more consistently on Supabase than just using a normal query outside a transaction.
Will need to test thoroughly before releasing.
> [Postgres] Revert "Use DECLARE CURSOR / FETCH for table snapshots."

- .changeset/chatty-boxes-repeat.md
- .changeset/serious-rivers-sin.md
- modules/module-postgres/src/replication/WalStream.ts
- modules/module-postgres/test/src/wal_stream.test.ts
- modules/module-postgres/test/src/wal_stream_utils.ts
- packages/service-core/src/storage/mongo/MongoBucketBatch.ts
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
Fixes regression from #150.
When starting replication, there are 4 different scenarios we cater for, depending on whether or not we have already completed the initial snapshot before, and whether or not we have a working logical replication slot.
```
1. haveSnapshot: false, haveWorkingSlot: false -> initial sync from scratch
2. haveSnapshot: true,  haveWorkingSlot: true  -> resume streaming replication
3. haveSnapshot: false, haveWorkingSlot: true  -> resume initial sync (new in #150)
4. haveSnapshot: true,  haveWorkingSlot: false -> initial sync from scratch (broken in #150)
```
The regression was in case 4 above - the slot would not get re-created, and replication would remain stuck. It can be triggered by something like replication lag falling too far behind, or anything else that …
> [Postgres] Fix slot recovery & improve log output

- .changeset/pretty-hotels-wonder.md
- .changeset/rare-knives-pump.md
- packages/service-core/src/storage/mongo/MongoSyncBucketStorage.ts
- packages/service-core/test/src/data_storage.test.ts
For reference see [Discord thread](https://discord.com/channels/1138230179878154300/1315652010518904893).
The resolved sync buckets would be missing entries which matched data after updating (moving) relational linked columns. 
The `getParameterSets` method was not returning the correct parameter sets after updating a `todo_list`'s `list_id` column. The query fetched all `bucket_parameters` that:
- Match the provided lookups (related to the input `list_ids`),
- Have `_id` values smaller than the current `checkpoint`, and
- Match the `group_id` (sync rules set).
The issue arose during the `$group` stage, where results were grouped by the `key` field alone. Since the `key` was not unique for different lookup values, updates introducing REMOVE entries with empty `bucket_parameters` could …
> Bucket Parameters Lookup Fix

- .changeset/six-chicken-decide.md
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/test/src/sql_functions.test.ts
When implementing the base64 uuid functionality we noticed that UUID foreign keys that were null were being transformed as empty string in the client.
This is because of the implementation of base64 function, which returns an empty string when passing it null. 
I guess changing this would be a breaking change, so with this function we should be able to handle null values without breaking existing functionality.
We followed the behavior of the SQLite IIF function described [here](https://www.sqlite.org/lang_corefunc.html#iif), which is essentially an if-else.
Alternatively it might make sense to change the base64 and hex functions so that they behave like the other functions, where they return null when inputted null. For example the length function.
> iif function based in the iif function of sqlite

- .changeset/small-socks-lay.md
- packages/service-core/src/storage/MongoBucketStorage.ts
For storage metrics over 2GB, the limit of a 32-bit signed integer is reached, so MongoDB returns the value as a bigint. OpenTelemetry metrics doesn't support bigint, so it just omit those metrics, resulting in no reported value.
This change forces conversion of these metrics to a number. We should not get any loss of precision in any realistic metric values, since `number` can still accurately store values up to 2^53-1.
> Handle storage metrics > 2GB

- .changeset/honest-cats-draw.md
- .changeset/many-shrimps-watch.md
- modules/module-mysql/src/common/mysql-to-sqlite.ts
- modules/module-mysql/src/replication/BinLogStream.ts
- modules/module-mysql/src/replication/MySQLConnectionManager.ts
- modules/module-mysql/src/utils/mysql-utils.ts
- modules/module-mysql/test/src/BinLogStream.test.ts
- modules/module-mysql/test/src/BinlogStreamUtils.ts
- modules/module-mysql/test/src/mysql-to-sqlite.test.ts
- packages/service-core/src/storage/SourceTable.ts
Fixes some issues with MySQL replication:
Timezone in timestamps were not handled correctly if the MySQL server is configured with a timezone other than UTC. The issue is that MySQL always returns timestamps in the session timezone, without any timezone indicator. So there is no way to know what we should configure the client `timezone` with if we don't know the server timezone.
The current tests also stored timestamps in the default/server timezone, but expected them to be returned in UTC timezone.
This changes:
1. Fix the tests to use `+00:00` timezone in literals.
2. Always set the timezone on the mysql connection used for queries: `SET time_zone = "+00:00"`. This does not appear to be needed for zongji.
When updating a row containing an update, the row was converted in-place to the …
> MySQL replication fixes

- .changeset/sweet-chairs-build.md
- modules/module-mongodb/src/replication/MongoRelation.ts
- modules/module-mongodb/test/src/mongo_test.test.ts
- packages/service-core/src/storage/mongo/MongoBucketBatch.ts
- packages/service-core/src/util/utils.ts
When replicating Postgres rows, in some edge cases we have toasted (missing) values in rows. We use `undefined` in our internal "current_data" storage to indicate these values are missing, and wait until we have all values before processing the row in sync rules.
With MongoDB replication, we always get the full document - we don't run into the case above. However, we had a bug where `undefined` values were kept as-is when replicating, triggering that logic. This caused rows with undefined values to not be replicated, without any indication why.
Our tests appeared to check for this case, but didn't in reality. MongoDB deprecated the undefined value in BSON, making it very difficult to actually insert an undefined value in the database. Our tests actually only tested for `null`, and never …
> MongoDB: Fix replication of undefined values

- .changeset/grumpy-cameras-breathe.md
- modules/module-mysql/src/replication/BinLogStream.ts
- modules/module-mysql/src/replication/zongji/zongji.d.ts
It was found that under some circumstance mysql replication stops without any errors, and only starts up correctly again when the powersync instance is restarted. We suspect that this may be happening to due an error on the replication connection that is not picked up by the Binlog listener. 
This adds a heartbeat mechanism on the listener's replication connection to ensure we timeously pick up when the connection has stalled.
> Added heartbeat to Mysql Binlog Listener connection

- .github/workflows/packages_release.yaml
https://github.com/powersync-ja/powersync-service/pull/136 removed the `GITHUB_TOKEN` from the service Dockerfile (since it is no longer needed). It also incorrectly removed the token from the Changesets release action. See failed action [run](https://github.com/powersync-ja/powersync-service/actions/runs/12669421548). This should fix the action.
> fix: release action

- .changeset/perfect-plums-cry.md
- modules/module-mysql/src/replication/BinLogStream.ts
This resolves the excessive memory consumption reported during initial snapshot replication.
> MySQL: Removed duplicate snapshot query stream invocation

- .changeset/swift-trains-behave.md
- libs/lib-mongodb/src/db/mongo.ts
- libs/lib-mongodb/src/index.ts
- modules/module-mongodb-storage/package.json
- modules/module-mongodb-storage/src/migrations/mongo-migration-store.ts
- modules/module-mongodb-storage/src/storage/MongoBucketStorage.ts
- modules/module-mongodb-storage/src/storage/implementation/MongoBucketBatch.ts
- modules/module-mongodb-storage/src/storage/implementation/MongoCompactor.ts
- modules/module-mongodb-storage/src/storage/implementation/MongoPersistedSyncRulesContent.ts
- modules/module-mongodb-storage/src/storage/implementation/MongoSyncBucketStorage.ts
- modules/module-mongodb-storage/src/storage/implementation/PersistedBatch.ts
- modules/module-mongodb-storage/src/storage/implementation/db.ts
- modules/module-mongodb-storage/src/storage/implementation/util.ts
- modules/module-mongodb/package.json
- modules/module-mongodb/src/api/MongoRouteAPIAdapter.ts
- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mongodb/src/replication/ChangeStreamReplicationJob.ts
- modules/module-mongodb/src/replication/MongoManager.ts
- modules/module-mongodb/src/replication/MongoRelation.ts
- modules/module-mongodb/test/src/change_stream.test.ts
- modules/module-mongodb/test/src/change_stream_utils.ts
- modules/module-mongodb/test/src/mongo_test.test.ts
- modules/module-mongodb/test/src/slow_tests.test.ts
- modules/module-mongodb/test/src/util.ts
- pnpm-lock.yaml
https://github.com/powersync-ja/powersync-service/pull/136 Moved common MongoDB logic to the `@powersync/lib-service-mongodb` package.
The bucket storage module's MongoDB connection is created using a utility from the shared library. The storage implementation checks certain caught `Error`s if they are instances of the MongoDB `MongoServerError` class. The `instanceof` checks fail if the shared library and the storage module use different versions of the MongoDB package. The core repository uses the same version throughout, but the hosted version's lockfile resolved different versions which caused the error detection to fail. Luckily the affected processes are retried, which did not cause any major issues.
This PR addresses the issue via two methods. 
A `isMongoServerError` utility …
> [Fix] Mongo Server Error Detection

- .changeset/violet-zebras-deliver.md
- packages/sync-rules/src/DartSchemaGenerator.ts
- packages/sync-rules/src/generators.ts
- packages/sync-rules/test/src/generate_schema.test.ts
Our new FlutterFlow integration will take a JSON string as a parameter and deserialize the schema from that. This avoids users having to write custom code for the schema.
> Add schema generator for FlutterFlow

- .changeset/poor-experts-care.md
https://github.com/powersync-ja/powersync-service/pull/186 made some changes to the `@powersync/service-lib-postgres` package which were missing a Changeset entry. The missing Changeset prevented the new features from being released, which causes issues downstream in our hosted repository when using the latest packages. The DockerHub image is not affected since the packages are locally sourced.
> [Fix] Missing Changeset

- .changeset/fast-monkeys-approve.md
- packages/sync-rules/src/TableValuedFunctions.ts
- packages/sync-rules/src/sql_functions.ts
- packages/sync-rules/test/src/sql_functions.test.ts
- packages/sync-rules/test/src/table_valued_function_queries.test.ts
Using the `->` operator with a missing value, for example `select '{}' -> 'test'`, would return `undefined` instead of `null`. We use SQLite types, so there should never be an `undefined` value.
This was specifically an issue when used together with `json_each`, for example `SELECT value as project_id FROM json_each(request.jwt() -> 'project_ids')`. This query would throw an error `Expected json_each to be called with a string, got undefined`, instead of treating it like an empty array like with `null` values.
This fixes `select '{}' -> 'test'` to return `null` correctly.
This also adds tests for all the following forms:
```sql
select '{"t": null}' -> 't' -- null in PowerSync, 'null' in SQLite
select '{}' -> 't' -- null in PowerSync and SQLite, fixed by this PR
select '{"t": null}' ->> …
```
> Fix -> operator on missing values to return null

- .changeset/shy-news-smell.md
- modules/module-mongodb/src/api/MongoRouteAPIAdapter.ts
- modules/module-mysql/src/api/MySQLRouteAPIAdapter.ts
- modules/module-postgres/src/api/PostgresRouteAPIAdapter.ts
- modules/module-postgres/test/src/checkpoints.test.ts
- modules/module-postgres/test/src/util.ts
- packages/service-core/src/api/RouteAPI.ts
- packages/service-core/src/routes/endpoints/checkpointing.ts
- packages/service-core/src/util/checkpointing.ts
- packages/service-core/src/util/util-index.ts
- packages/service-core/src/util/utils.ts
The issue is a race condition that sometimes causes a new write checkpoint to not be acknowledged on an existing connection.
Symptoms of the issue:
1. The client would stay in `downloaded: true` state.
2. If the client was offline before, changes made in that offline period would not be applied.
3. Once an additional change is made on the backend db, the write checkpoint will be acknowledged and the issue will be resolved.
The issue appeared to more prevalent on React Native than on other platforms, likely due to the specific timing of requests, although the underlying cause is on the service.
The expected sequence of events with a write checkpoint is:
1. Client has an active sync connection, listening for new checkpoints.
5. Client calls write-checkpoint2.json.
6. The service creates a …
> Fix write checkpoint race condition

- .github/workflows/test.yml
In #203 I enabled running tests on pull_request, which allows running tests when a PR is made from a fork.
The issue is that it now results in a total of 29 checks being run for every commit. This changes the jobs to only run on push or _external_ pull request, to avoid that duplication.
See:
1. This PR, running all checks on push, skipping all checks on pull_request.
2. #206 as an example of a forked PR, running all checks on pull_request.
> Limit GH actions to only run on push or external PR

- .github/workflows/test.yml
- modules/module-postgres/test/src/checkpoints.test.ts
#201 introduced a new test that turned out to be quite unstable. This increases the time thresholds to make it more stable.
This also updates `supercharge/mongodb-github-action@1.12.0` for some stability fixes in starting the container, and switches to using mongodb 8.0 by default. The mongodb modules are still tested on 6.0 and 7.0.
> Improve test stability

- .changeset/config.json
- packages/service-core/package.json
- packages/service-core/test/src/auth.test.ts
- service/package.json
1. Fix the versions of `@powersync/service-core` - these will now be versioned together  `@powersync/service-image`. That basically means that the version of `@powersync/service-core` would be bumped even if there are only changes in the service image.
2. Bump to v1.6.999, so that the next version will be 1.7.0, aligning with our cloud image versions.
3. Sneak in some test stability improvements and fixes to warnings.
> Prepare for v1.7.0

- .changeset/rare-birds-peel.md
- modules/module-mongodb-storage/src/storage/implementation/MongoSyncBucketStorage.ts
- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mongodb/src/replication/MongoRelation.ts
- modules/module-mongodb/test/src/change_stream.test.ts
- modules/module-mysql/src/replication/BinLogStream.ts
- modules/module-postgres-storage/src/storage/PostgresSyncRulesStorage.ts
- modules/module-postgres-storage/src/types/models/SourceTable.ts
- packages/service-core/src/storage/SourceEntity.ts
- packages/service-core/src/storage/SourceTable.ts
Specific scenario is when all of the following conditions are met:
1. We're replicating from an Atlas Flex instance.
2. There were changestream events recorded while the PowerSync service is paused.
3. We're only replicating from a single database.
Then we've observed an ns with for example `{db: '67b83e86cd20730f1e766dde_ps'}`, instead of the expected `{db: 'ps'}` on the change stream.
This caused issues on multiple levels internally:
1. We only used the collection name as the "relation_id" for the internal "source table" (bug 1).
2. The storage module then detected the equivalent of a renamed collection, since it saw the same relation_id, but a different schema.
3. We then truncate the table, but never did a snapshot of the "new" collection (bug 2).
4. This resulted in the collection …
> Fix truncating collections from MongoDB source database

- .changeset/rotten-items-explode.md
- .changeset/rotten-nails-cheat.md
- .changeset/six-dragons-whisper.md
- modules/module-mongodb-storage/src/storage/implementation/MongoCompactor.ts
- modules/module-mongodb-storage/test/src/storage_compacting.test.ts
- modules/module-postgres-storage/src/storage/PostgresCompactor.ts
- modules/module-postgres-storage/test/src/storage_compacting.test.ts
- packages/service-core-tests/src/tests/register-compacting-tests.ts
- packages/service-core/src/storage/SyncRulesBucketStorage.ts
A bug was recently identified in the Postgres compacting logic. Compacting can fail due to an "unexpected PUT operation" error.
The Postgres compacting operations logic contained an error in the bucket operation processing logic. 
The current Postgres windowing logic functions as follows:
- Bucket operations are processed in a moving window of batched operations.
- Each batch queries over all buckets. 
- On the second batch, the window is still over all buckets, only limiting the last `op_id`.
Suppose the scenario:
-  There are two buckets: `bucket1` and `bucket2`, each with 8k ops.
- `bucket1` is ops [1:8_000]`, `bucket2` is ops `[8_001:16_000]`.
- Batch 1 returns 8k ops from `bucket1`, and 2k ops `[14_001:16_000]` from `bucket2`.
- For batch 2, the compactor queries for `op_id < …
> Postgres Compact Fix

- .changeset/hot-pets-itch.md
- modules/module-mongodb-storage/src/storage/implementation/MongoBucketBatch.ts
- modules/module-mongodb-storage/src/storage/implementation/OperationBatch.ts
- modules/module-mongodb-storage/src/storage/implementation/PersistedBatch.ts
- modules/module-mongodb/src/replication/ChangeStream.ts
In some cases, MongoDB initial replication replicated at a rate as low as 150 documents/second, while we're aiming for 5-10k/second. After some investigation, the main bottleneck appears to be _reading_ the documents from the source database, rather than writing to bucket storage.
I can't figure out why, but reading the documents using a MongoDB session appears to be the main culprit. Using the session, it could take as long as 10-20s to read 10k documents in some cases. This is not consistent, which makes it difficult to test. Without the session, that drops down to 0.5-1s for the same 10k documents. ~The latter is fairly consistent.~
This changes the query to not use a session anymore. Initially we used a session for snapshot reads, but that is not required anymore, so there is no good …
> [MongoDB] Improve initial replication performance

- .changeset/chilly-flowers-fix.md
- .github/workflows/test.yml
- modules/module-postgres/src/replication/WalStream.ts
Previously, if we got 100k transactions each with a single operation, we'd commit/flush that 100k times to the bucket storage. Flushing is slow - in the case of a storage cluster under load, this can take 100-500ms per flush, resulting in throughput of less than 10 transactions per second.
Lucky for us, Postgres already chunks messages together in the replication stream. So now we look ahead in the current chunk to see if there are any more commit messages. If there are, we only flush/commit on the _last_ one. This means if we get many transactions in a single chunk, they are all batched together in a single flush to the bucket storage.
For reference, we already have similar behavior in our MongoDB replication implementation.
In theory we could also batch transactions across multiple …
> [Postgres] Optimize transaction replication throughput

- .changeset/fuzzy-items-look.md
- modules/module-mysql/src/replication/BinLogStream.ts
Previously, replication could fail with an unhelpful error like this:
```
Replication error Can't add new command when connection is in closed state
```
This error was raised during ROLLBACK, hiding the actual underlying issue.
This now logs the rollback error, then continues throwing the original error.
> [MySQL] Fix errors being hidden by ROLLBACK failure

- .changeset/hungry-planets-smell.md
- modules/module-mongodb/src/module/MongoModule.ts
For testing MongoDB connections, we use a relatively short connection timeout (specifically `serverSelectionTimeoutMS`), since that is the only way to detect clusters we cannot connect to due to IP access list issues. However, the timeout of 1000ms was too short when connecting to a cluster in for example AWS `ap-southeast-2`, from our test node in `us-east-1`.
This increases the timeout sufficiently to cover these cases.
> Increase connection timeout for MongoDB

- .changeset/warm-coins-wave.md
- packages/service-core/src/routes/endpoints/probes.ts
- packages/service-core/test/src/routes/probes.integration.test.ts
- packages/service-core/test/src/routes/probes.test.ts
The HTTP liveness probe currently always returns a 400 HTTP response code in the API service mode. This is due to the `touched_at` value not being updated in the last 10 seconds. Generally, in the API mode, the PowerSync service should be alive if it returned any HTTP response. The logic has been updated to always return 200 if the service has been started in the API mode.
The current logic is preserved if the service is started in the UNIFIED mode. The liveness probe will return a 400 HTTP status code if the replicator engine has not updated the last `touched_at` value in 10 seconds. The replicator loop is most likely stuck if the touched at value has not been updated.
The HTTP probes are still not yet functional if the service was started purely in the SYNC mode. Future work will …
> HTTP Liveness Probe Stopgap Fix

- .changeset/famous-spoons-whisper.md
- modules/module-mysql/dev/docker/mysql/docker-compose-57.yaml
- modules/module-mysql/dev/docker/mysql/init-scripts/mysql_57.sql
- modules/module-mysql/src/common/mysql-to-sqlite.ts
- modules/module-mysql/test/src/mysql-to-sqlite.test.ts
MySQL uses the same type code for Varbinary and Varchar columns. This then requires additional interrogation of the column metadata to correctly determine the type. Previously we just checked the binary flag in the column metadata to determine if a column was in fact Varbinary. But it turns out Varchar columns with binary encoding set will also have the binary flag set, leading to mis-identifcation. Instead we now check the characterSet for the column for the binary characterSet which seems to only be set for actual Varbinary columns
> MySQL: Reworked Varchar/Varbinary column identification

- .changeset/shaggy-actors-confess.md
- packages/service-core-tests/src/tests/register-sync-tests.ts
- packages/service-core/src/sync/sync.ts
Disable interrupting checkpoints for now.
There is a bug with interrupting checkpoints where:
1. User is in the middle of syncing a large batch of data (for example initial sync).
2. A new checkpoint comes in, which interrupts the batch.
3. However, the new checkpoint does not contain any new data for this connection, so nothing further is synced.
This then causes the client to wait indefinitely for the remaining data or checkpoint_complete message. That is only resolved when a new checkpoint comes in that does have data for this connection, or the connection is restarted.
This is typically triggered when:
1. A user is downloading a large set of data, _and_:
2. New data updates are coming in at a high rate, _without_ modifying any data for that specific user.
Interrupting checkpoints is …
> Disable checkpoint interruption

- .changeset/gentle-coins-lie.md
- modules/module-mongodb-storage/src/storage/implementation/MongoSyncBucketStorage.ts
The `deleteMany` for clearning bucket_parameters data used a filter like this:
```js
"key": {
"$gte": {
"g": 3,
"t": MinKey(),
"k": MinKey()
},
"$lt": {
"g": 3,
"t": MaxKey(),
"k": MaxKey()
}
}
```
This followed the same pattern as the _id filters on other collections. However, there is no direct index on `key`, only this index:
```js
await database.bucket_parameters.createIndex(
{
'key.g': 1,
lookup: 1,
_id: 1
},
{ name: 'lookup1' }
);
```
So in this case we can just use a simpler filter on `key.g`, to achieve the same thing but using an index.
> Fix deleteMany for bucket_parameters to use an index

- .changeset/friendly-rings-accept.md
- libs/lib-mongodb/src/db/mongo.ts
- modules/module-mongodb/src/common/MongoLSN.ts
- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mongodb/src/replication/ChangeStreamReplicationJob.ts
- modules/module-mongodb/test/src/change_stream_utils.ts
- modules/module-mongodb/test/src/resume.test.ts
- modules/module-mongodb/test/src/resume_token.test.ts
- packages/service-errors/src/codes.ts
Our current implementation used resume tokens received from change stream events to resume the stream after a restart.
However, if the source collections do not receive writes, we do not receive any actual events, and the token is never advanced. If the source cluster receives many other oplog events, resuming the stream can become very slow after a while, or time out completely. Once it starts timing out, we don't have a way to recover other than restarting replication from scratch. The timeout typically shows up as an error "connection 2 to 159.41.94.47:27017 timed out". The error can be simulated by reducing `socketTimeoutMS` significantly (say 50ms).
MongoDB does however provide new resume tokens even when there are no events: …
> [MongoDB] Fix resume token handling when no events are received

- .changeset/old-ties-retire.md
- .changeset/small-clouds-collect.md
- modules/module-mongodb-storage/src/storage/MongoBucketStorage.ts
- packages/service-core/src/metrics/open-telemetry/OpenTelemetryMetricsFactory.ts
- packages/service-core/src/storage/storage-metrics.ts
The storage metric `powersync_parameter_storage_size_bytes` was missing when there were not any parameter queries in the sync rules.
> Fix missing parameter storage metrics

- .changeset/pretty-eagles-fail.md
- modules/module-mongodb-storage/src/storage/implementation/MongoSyncBucketStorage.ts
- modules/module-mongodb-storage/test/src/storage_sync.test.ts
- modules/module-mongodb/test/src/change_stream_utils.ts
- modules/module-mysql/test/src/BinlogStreamUtils.ts
- modules/module-postgres-storage/src/storage/PostgresSyncRulesStorage.ts
- modules/module-postgres-storage/test/src/storage.test.ts
- modules/module-postgres/test/src/wal_stream_utils.ts
- packages/service-core-tests/src/test-utils/general-utils.ts
- packages/service-core-tests/src/tests/register-compacting-tests.ts
- packages/service-core-tests/src/tests/register-data-storage-tests.ts
- packages/service-core/src/storage/SyncRulesBucketStorage.ts
- packages/service-core/src/sync/sync.ts
- packages/service-core/src/util/protocol-types.ts
With Postgres bucket storage, there are scenarios when a data line would have `has_more: false`, even though the bucket has more data. This leads to a checksum failure for the bucket, and the entire bucket re-downloaded.
This only occurred when there are multiple different buckets returned in a single `getBucketDataBatch()` call, with the first bucket returned not having this issue. This means the client did make progress on each sync attempt, and did not repeatedly run into the same checksum failure. So in most cases, users would not directly see the issue, but sync would take longer than it should.
This fixes the has_more logic to cover this case, with new tests.
The tests picked up another couple of consistency issues with batch metadata. None of these caused any visible symptoms on …
> Fix and test "has_more" for data batches

- .changeset/clever-kangaroos-thank.md
- libs/lib-services/src/router/endpoint.ts
- libs/lib-services/src/router/router-definitions.ts
- modules/module-postgres/src/auth/SupabaseKeyCollector.ts
- packages/rsocket-router/src/router/ReactiveSocketRouter.ts
- packages/service-core/src/auth/CachedKeyCollector.ts
- packages/service-core/src/auth/CompoundKeyCollector.ts
- packages/service-core/src/auth/KeyCollector.ts
- packages/service-core/src/auth/KeyStore.ts
- packages/service-core/src/auth/RemoteJWKSCollector.ts
- packages/service-core/src/auth/auth-index.ts
- packages/service-core/src/auth/utils.ts
- packages/service-core/src/routes/auth.ts
- packages/service-core/src/routes/configure-rsocket.ts
- packages/service-core/src/routes/router.ts
- packages/service-core/test/src/auth.test.ts
- packages/service-errors/src/codes.ts
- packages/service-errors/src/errors.ts
This aims to provide more useful error messages when auth fails, by:
1. Using our own error codes and messages, instead of the defaults from JOSE.
2. Add additional details on the token and/or relevant configuration in the service logs (but not the error response).
For each example, the first line is in the error response, second line is in logs only.
In most of these examples, a big gain is having the token header and payload in the logs. In some cases, the details of the key that the token is compared to may also help. The cause in the logs also help.
```js
// unknown kid
{"code":"PSYNC_S2101","status":401,"description":"Could not find an appropriate key in the keystore. The key is missing or no key matched the token KID","name":"AuthorizationError"}
"configurationDetails":"Known kid …
```
> Improve auth errors

- .changeset/happy-taxis-lick.md
- .changeset/wild-maps-brake.md
- packages/rsocket-router/src/router/ReactiveSocketRouter.ts
- packages/rsocket-router/src/router/types.ts
- packages/rsocket-router/tests/src/requests.test.ts
- packages/service-core/src/routes/configure-rsocket.ts
- packages/service-errors/src/codes.ts
- packages/service-errors/src/errors.ts
With the ongoing work to move more parts of the sync logic into the core extension, client SDKs no longer need to implement the BSON deserialization logic themselves (instead relying on our Rust decoder to take care of that). But while that covers response handing, clients are still responsible for crafting RSocket _requests_ (e.g. to transmit tokens or a user agent).
At the moment, our code to handle RSocket requests always assumes that the connection data and metadata will be encoded as BSON. This is unfortunate for clients, because they then need to ship a BSON encoder for the sole purpose of creating these tiny request payloads (and especially on JavaScript, our dependency on the BSON library requires special compilation support for `@powersync/common`). So while we continue to serve …
> Allow JSON request payload for RSocket

- .changeset/config.json
- .changeset/lemon-hotels-fold.md
- packages/schema/.gitignore
- packages/schema/CHANGELOG.md
- packages/schema/LICENSE
- packages/schema/README.md
- packages/schema/package.json
- packages/schema/src/index.ts
- packages/schema/src/scripts/compile-json-schema.ts
- packages/schema/tsconfig.json
- packages/service-core/src/util/config/collectors/config-collector.ts
- packages/types/package.json
- packages/types/src/config/PowerSyncConfig.ts
- pnpm-lock.yaml
This adds a JSON Schema for the PowerSync service configuration file. This schema can be used by self hosters to validate and get autocomplete suggestions in their configuration YAML files.
This uses the existing PowerSyncConfig TS-Codec definition to generate the schema. Additional meta data is added in order to provided a description/comment for fields. 
Our modular architecture uses a distributed configuration declaration. The `service-core` package declares a generic configuration structure, while the various modules declare the specific connection configuration. The schema generated here is a combination of the various module configuration options. This should give the best DX for validations and autocomplete.
The schema is compiled and shipped in a new `@powersync/service-schema` …
> JSON schema

- .changeset/cool-seas-compete.md
- packages/service-core-tests/src/tests/register-sync-tests.ts
- packages/service-core/src/sync/BucketChecksumState.ts
- packages/service-core/src/sync/sync.ts
- packages/service-core/test/src/sync/BucketChecksumState.test.ts
This restores support for interrupting checkpoints (the functionality was disabled in https://github.com/powersync-ja/powersync-service/pull/236 due to a flaw where new checkpoints on unrelated bucket would interrupt sync).
To restore this functionality, we're expanding the work we're doing while the previous sync iteration is active: Instead of just waiting for a new checkpoint from storage, we're also building the new checkpoint line preemptively. If the new checkpoint does not result in a `checkpoint` line for the connection, we do nothing and keep waiting for the next checkpoint. 
This should be safe because the stateful logic to build checkpoint lines does not update its internal state if no line ends up being built.
> Dont interrupt sync for unrelated checkpoint

- .changeset/clever-months-travel.md
- libs/lib-postgres/package.json
- libs/lib-services/package.json
- libs/lib-services/src/index.ts
- libs/lib-services/src/logger/Logger.ts
- libs/lib-services/src/logger/logger-index.ts
- libs/lib-services/src/router/router-response.ts
- modules/module-mongodb-storage/package.json
- modules/module-mongodb/package.json
- modules/module-mysql/package.json
- modules/module-postgres-storage/package.json
- modules/module-postgres/package.json
- packages/rsocket-router/package.json
- packages/rsocket-router/src/router/ReactiveSocketRouter.ts
- packages/rsocket-router/tests/src/requests.test.ts
- packages/service-core/package.json
- packages/service-core/src/routes/configure-fastify.ts
- packages/service-core/src/routes/configure-rsocket.ts
- packages/service-core/src/routes/endpoints/socket-route.ts
- packages/service-core/src/routes/endpoints/sync-stream.ts
- packages/service-core/src/routes/route-register.ts
- packages/service-core/src/routes/router.ts
- packages/service-core/src/sync/BucketChecksumState.ts
- packages/service-core/src/sync/RequestTracker.ts
- packages/service-core/src/sync/sync.ts
- packages/sync-rules/package.json
- pnpm-lock.yaml
Two general logging changes:
Pass a child logger instance through via the Context, so that we can configure metadata on the logger that applies to the entire request. This means that request logs will include common context, making it easier to debug:
1. user_agent
2. rid (unique request id, to correlate with other logs)
3. user_id
4. client_id
Passing the logger through the entire stack could be a pain in some cases. Right now, this is mostly limited to sync requests, so not too bad. If we start using it in many more places, [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) would be a good way to handle this automatically.
For each completed stream, instead of just logging the total number of synced operations, this logs more details. Example:
``` …
```
> Additional log metadata on sync requests

- modules/module-mongodb-storage/test/src/__snapshots__/storage_sync.test.ts.snap
- modules/module-postgres-storage/test/src/__snapshots__/storage_sync.test.ts.snap
- packages/service-core-tests/src/tests/register-sync-tests.ts
Follows on #239.
This just adds a test for another checkpoint interruption scenario, to improve coverage since the `BucketChecksumState` implementation is quite finicky.
No actual changes in this PR.
> Add another sync checkpoint interruption test

- packages/service-errors/src/codes.ts
> Fixed some typos in error code descriptions

- .changeset/little-beans-carry.md
- modules/module-mongodb-storage/src/storage/implementation/MongoBucketBatch.ts
- modules/module-mongodb-storage/src/storage/implementation/PersistedBatch.ts
- modules/module-postgres-storage/src/storage/batch/PostgresBucketBatch.ts
- modules/module-postgres-storage/src/storage/batch/PostgresPersistedBatch.ts
- packages/service-core-tests/src/tests/register-data-storage-tests.ts
- packages/service-core/src/routes/endpoints/sync-rules.ts
- packages/service-core/src/sync/BucketChecksumState.ts
- packages/service-core/src/sync/sync.ts
- packages/sync-rules/src/BaseSqlDataQuery.ts
- packages/sync-rules/src/BucketDescription.ts
- packages/sync-rules/src/SqlBucketDescriptor.ts
- packages/sync-rules/src/SqlDataQuery.ts
- packages/sync-rules/src/SqlParameterQuery.ts
- packages/sync-rules/src/SqlSyncRules.ts
- packages/sync-rules/src/StaticSqlParameterQuery.ts
- packages/sync-rules/src/TableValuedFunctionSqlParameterQuery.ts
- packages/sync-rules/src/events/SqlEventDescriptor.ts
- packages/sync-rules/src/events/SqlEventSourceQuery.ts
- packages/sync-rules/src/request_functions.ts
- packages/sync-rules/src/schema-generators/SchemaGenerator.ts
- packages/sync-rules/src/sql_filters.ts
- packages/sync-rules/src/types.ts
- packages/sync-rules/test/src/data_queries.test.ts
- packages/sync-rules/test/src/parameter_queries.test.ts
- packages/sync-rules/test/src/static_parameter_queries.test.ts
- packages/sync-rules/test/src/sync_rules.test.ts
- packages/sync-rules/test/src/table_valued_function_queries.test.ts
This contains no functional changes, but does contain some breaking "api" changes for the `@powersync/service-sync-rules` package. This is primarily to clean up the code to make it easier to make larger changes that I'll be working on soon.
Main changes:
1. Make individual query classes "immutable" for the most part. This removes the need for nullable fields while building the instances, making it clear which fields may actually be undefined.
2. Change field names to camelCase for consistency.
3. Remove some unused fields, and document the others.
> Cleanup sync rules implementation

- .changeset/beige-clocks-mix.md
- packages/service-core/src/sync/sync.ts
- packages/service-core/src/util/protocol-types.ts
- test-client/src/util.ts
The `data` field in `OplogEntry` will always be a nullable string, we don't store contents as an object directly.
This was a bit confusing to me when writing the new sync client for the core extension, I thought the `Record` representation was something we had to deal with. This fixes the type annotations to make it clear that that's not true.
> Clarify oplog entry format

- .changeset/beige-clouds-cry.md
- modules/module-mongodb/src/api/MongoRouteAPIAdapter.ts
- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mongodb/src/replication/MongoRelation.ts
- modules/module-mongodb/test/src/change_stream_utils.ts
- packages/service-core/src/api/RouteAPI.ts
When replicating from a MongoDB database, we use the `_powersync_checkpoints` collection for multiple purposes:
1. To detect the end of a transaction.
2. To create write checkpoints.
3. To dynamically "batch" updates from multiple transactions efficiently.
This change specifically concerns the last point - batching. The process works as follows:
1. Whenever we receive a change, and haven't started a "batch" yet, we create a new "checkpoint" document.
2. We wait for that document to be present in the change stream.
3. Once we get that document, we flush/commit the changes.
On a mostly-idle database, we should get that checkpoint document back almost immediately, triggering a flush ASAP. While on very busy databases where a replication lag builds up, we only get that document back once …
> [MongoDB] Fix replication batching

- modules/module-mongodb-storage/src/storage/implementation/MongoBucketBatch.ts
- packages/service-core-tests/src/tests/register-data-storage-tests.ts
Fixes a regression from #276. The bug is not any release, so not adding a changeset.
#276 refactored custom write checkpoints to be flushed together with other changes when using MongoDB storage, to make it easy to associate an op_id with it. The bug is that if there were no other changes to flush, the write checkpoints weren't flushed either. This fixes it, and adds a test to reproduce.
> Fix custom write checkpoints

- .changeset/witty-cougars-build.md
- packages/service-core/src/routes/configure-rsocket.ts
- packages/service-core/src/routes/router.ts
#258 improved auth errors in general, but it was not correctly propagated for websocket connections, resulting in a generic "[PSYNC_S2106] Authentication required" message. This fixes it to correctly propagate the token errors, same as for http streams.
> Correctly propagate auth errors for websockets

- .changeset/shy-pugs-teach.md
- modules/module-mongodb/src/replication/ChangeStream.ts
- modules/module-mongodb/src/replication/MongoSnapshotQuery.ts
- modules/module-mongodb/test/src/chunked_snapshot.test.ts
This is a regression in v1.13.0.
In #163, we changed initial snapshot queries on MongoDB to chunk on _id, using `{_id: {$gt: ...}}` queries to filter out earlier chunks. The issue is that when the same collection uses different types for the `_id` field, the `$gt` operator only returns documents with the same type. That meant that when you have a large collection with for example both string and ObjectId _ids, only the documents with string `_id` would replicate in the initial snapshot.
This would be visible in the logs, with the collection finishing replicating with mismatching counts, such as:
```
Replicating "mydb"."mycollection" 12356/~23000
```
This changes the snapshot query to `{ $expr: { $gt: ['$_id', { $literal: ... }] } }`. This is almost the same, but the `$expr` version …
> Fix MongoDB replication with mixed _id types

- .changeset/dull-pumas-punch.md
- libs/lib-mongodb/src/db/errors.ts
- libs/lib-mongodb/src/db/mongo.ts
- modules/module-mongodb-storage/src/storage/implementation/MongoSyncBucketStorage.ts
- packages/service-errors/src/codes.ts
- packages/service-errors/src/errors.ts
Specify a limit of 40s for each query, instead of relying on the connection socket timeout. The most common cause is a timeout when computing checksums on buckets with millions of operations. We can often recover by retrying the query - the second attempt is faster since the data would be cached in database memory.
Before:
```
[PSYNC_2001] Something went wrong
connection 10 to a.b.c.d:27017 timed out
```
Now:
```
[PSYNC_S2403] Query timed out while reading checksums
```
> Specify maxTimeMs for MongoDB storage queries

- .changeset/fifty-pens-hammer.md
- .changeset/sharp-bees-serve.md
- packages/service-core/src/routes/configure-fastify.ts
- packages/service-core/src/routes/route-register.ts
- packages/service-errors/src/errors.ts
The sync service has custom error types used to respond with error descriptions, like:
```
{"error":{"code":"PSYNC_S2106","status":401,"description":"Authentication required","name":"AuthorizationError"}}
```
When requesting an endpoint that doesn't exist, the sync service also responds with an error. That response has an incompatible structure though:
```
{"message":"Route GET:/foo/bar not found","error":"Not Found","statusCode":404}
```
That response manages to [crash the error handler](https://discord.com/channels/1138230179878154300/1396435049938944081/1396435049938944081) in the Dart SDK, leading to a confusing error message there.
This PR installs a custom 404 handler on fastify to ensure the responses are consistent.
> Make 404 errors consistent with other error responses

- .changeset/shaggy-fireants-prove.md
#293 changed the `application_name` used in postgres connections from `PowerSync` to `powersync/${version}`. This made it into the 1.13.4 release, but the changeset in the jpgwire package was missing, so this never applied the change in the released npm packages.
This just adds a changeset to allow doing that release.
> Change Postgres application_name

- packages/service-core/src/api/diagnostics.ts
Follows on #304. This changes the initial warning threshold from 2 minutes to 5 minutes for the initial release, to avoid too many false positives while we're still testing out the feature.
No changeset included since the change hasn't been released yet.
> Tweak "No replicated commit" warning

- test-client/src/load-testing/rsocket-worker.ts
- test-client/tsconfig.json
This avoids the error below on idle connections for `pnpm concurrent-connections --mode websocket`:
```
Error: Closed. Original cause [Error: WebsocketDuplexConnection: Socket closed unexpectedly.].
```
The websocket mode still does not include retries, but this makes it a little more stable.
> [test-client]: set websocket keepalives

- modules/module-mongodb-storage/src/storage/implementation/MongoBucketBatch.ts
- modules/module-postgres-storage/src/storage/batch/PostgresBucketBatch.ts
- packages/service-core-tests/src/tests/register-data-storage-tests.ts
- packages/service-core/src/storage/BucketStorage.ts
- packages/sync-rules/src/SqlBucketDescriptor.ts
- packages/sync-rules/src/SqlSyncRules.ts
- packages/sync-rules/src/events/SqlEventDescriptor.ts
- packages/sync-rules/src/streams/from_sql.ts
- packages/sync-rules/src/streams/stream.ts
- packages/sync-rules/src/types.ts
- packages/sync-rules/src/utils.ts
- packages/sync-rules/test/src/compatibility.test.ts
#331 introduced `SqliteInputValue` and the `CustomSqliteValue` class to represent values that may have to be synced differently depending on compatibility options. The original idea was that each sync stream and SQL bucket or event descriptor would apply their compatibility options when mapping the row, so that`CustomSqliteValue`s are temporary instances living between the replicator and sync rules.
That approach is flawed in two ways:
1. It was based on the assumption that different bucket descriptors may have different compatibility options, which is no longer the case (there's one global compatibility context for sync rules). So applying the mapping at the level of the individual stream or sync rule can be inefficient.
2. Worse, because we may be trying to store rows to recover from …
> Avoid persisting SqliteInputValues
